TrajectoryPlannerROS:
  world_model: costmap
  holonomic_robot: false

  acc_lim_x: 0.25
  acc_lim_y: 0.0
  acc_lim_th: 0.5
  max_vel_x: 1.0
  min_vel_x: 0.05
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.1
  escape_vel: -0.1
  escape_reset_dist: 0.2
  escape_reset_theta: 0.25
  oscillation_reset_dist: 0.05

  yaw_goal_tolerance: 0.25
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true

  sim_time: 2.0
  sim_granularity: 0.05
  angular_sim_granularity: 0.08
  vx_samples: 10
  vtheta_samples: 10
  controller_frequency: 10.0

  meter_scoring: true
  path_distance_bias: 0.6
  goal_distance_bias: 1.2
  occdist_scale: 0.01
  heading_lookahead: 0.325
  heading_scoring: false
  dwa: true

  prune_plan: true
