local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.05

  obstacle_range: 5.0
  raytrace_range: 6.0
  max_obstacle_height: 1.2

  robot_radius: 0.2
  inflation_radius: 0.2
  footprint_clearing_enabled: true
  track_unknown_space: false

  plugins:
    - {name: map_layer, type: "costmap_2d::StaticLayer"}
    - {name: scan_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: sonar_layer, type: "range_sensor_layer::RangeSensorLayer"}
    # - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  map_layer:
    map_topic: /map
    allow_size_updates: true
    subscribe_to_updates: false
    track_unknown_space: false
    use_maximum: false

  scan_layer:
    observation_sources: laser_scan_sensor bumper_sensor
    laser_scan_sensor:
      sensor_frame: laser_optical_link
      expected_update_rate: 0.15
      data_type: LaserScan
      topic: /scan
      marking: true
      clearing: true
    bumper_sensor:
      sensor_frame: bumper_link
      expected_update_rate: 0.25
      data_type: PointCloud
      topic: /bumper/collisions
      marking: true
      clearing: true

  sonar_layer:
    topics: [/left_sonar, /front_sonar, /right_sonar]
    clear_on_max_reading: true
