<?xml version="1.0"?>
<robot name="sensors" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="rplidar_a1m8r1_mass" value="0.190"/>
  <xacro:property name="rplidar_a1m8r1_diameter" value="0.070"/>
  <xacro:property name="rplidar_a1m8r1_length" value="0.0245"/>

  <xacro:macro name="rplidar-a1m8r1" params="name">
    <link name="${name}_link">
      <inertial>
        <origin xyz="0 0 0.04175"/>
        <mass value="${rplidar_a1m8r1_mass}"/>
        <xacro:cylinder_inertia mass="${rplidar_a1m8r1_mass}"
                                radius="${rplidar_a1m8r1_diameter / 2}"
                                length="${rplidar_a1m8r1_length}"/>
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://airi_description/media/sensors/rplidar_a1m8r1.stl"
                scale="0.001 0.001 0.001"/>
        </geometry>
      </visual>
    </link>
    <link name="${name}_optical_link"/>
    <joint name="${name}_spin_joint" type="fixed">
      <parent link="${name}_link"/>
      <child link="${name}_optical_link"/>
      <origin xyz="0 0 0.045"/>
    </joint>
    <gazebo reference="${name}_optical_link">
      <sensor type="ray" name="${name}">
        <pose>0 0 0 0 0 0</pose>
        <visualize>false</visualize>
        <update_rate>10</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>360</samples>
              <resolution>1</resolution>
              <min_angle>${-PI}</min_angle>
              <max_angle>${PI}</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.15</min>
            <max>6.0</max>
            <resolution>0.005</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <!-- Noise parameters based on published spec for RPLidar A1M8 rev1
                 laser achieving "+-1%" accuracy at range < 6m. A mean of 0.0m and
                 stddev of 0.00577m will put 99.7% of samples within +-1%
                 of the true reading. -->
            <mean>0.0</mean>
            <stddev>0.00577</stddev>
          </noise>
        </ray>
        <plugin name="${name}_controller" filename="libgazebo_ros_laser.so">
          <topicName>${name}</topicName>
          <frameName>${name}_optical_link</frameName>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>

  <xacro:property name="hcsr04_sonar_mass" value="0.020"/>
  <xacro:property name="hcsr04_sonar_height" value="0.015"/>
  <xacro:property name="hcsr04_sonar_length" value="0.045"/>
  <xacro:property name="hcsr04_sonar_width" value="0.020"/>

  <xacro:macro name="hcsr04-sonar" params="name">
    <link name="${name}_link">
      <inertial>
        <origin xyz="${hcsr04_sonar_height / 2} 0 0" rpy="0 ${PI/2} 0"/>
        <mass value="${hcsr04_sonar_mass}"/>
        <xacro:box_inertia mass="${hcsr04_sonar_mass}"
                           width="${hcsr04_sonar_width}"
                           length="${hcsr04_sonar_length}"
                           height="${hcsr04_sonar_height}"/>
      </inertial>
      <visual>
        <origin rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <mesh filename="package://airi_description/media/sensors/hcsr04.stl"
                scale="0.001 0.001 0.001"/>
        </geometry>
      </visual>
    </link>
    <gazebo reference="${name}_link">
      <sensor type="ray" name="${name}">
        <pose>0 0 0 0 0 0</pose>
        <visualize>false</visualize>
        <update_rate>10</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>10</samples>
              <resolution>1</resolution>
              <min_angle>${-15.0 * PI / 180.0}</min_angle>
              <max_angle>${15.0 * PI / 180.0}</max_angle>
            </horizontal>
            <vertical>
              <samples>10</samples>
              <resolution>1</resolution>
              <min_angle>${-15.0 * PI / 180.0}</min_angle>
              <max_angle>${15.0 * PI / 180.0}</max_angle>
            </vertical>
          </scan>
          <range>
            <min>0.02</min>
            <max>2.0</max>
            <resolution>0.02</resolution>
          </range>
        </ray>
        <plugin name="${name}_controller" filename="libgazebo_ros_range.so">
          <topicName>${name}</topicName>
          <frameName>${name}_link</frameName>
          <!-- See https://forum.arduino.cc/index.php?topic=243076.0 for reference -->
          <gaussianNoise>0.005</gaussianNoise>
          <radiation>ULTRASOUND</radiation>
          <fov>${2 * 15.0 * PI / 180.0}</fov>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>

  <xacro:property name="ky033_ranger_mass" value="0.020"/>
  <xacro:property name="ky033_ranger_thickness" value="0.0016"/>
  <xacro:property name="ky033_ranger_length" value="0.03118"/>
  <xacro:property name="ky033_ranger_width" value="0.014"/>

  <xacro:macro name="ky033-ranger" params="name">
    <link name="${name}_link">
      <inertial>
        <origin xyz="-0.010 ${ky033_ranger_thickness / 2} -0.0105" rpy="${PI/2} 0 ${-PI/2}"/>
        <mass value="${ky033_ranger_mass}"/>
        <xacro:box_inertia mass="${ky033_ranger_mass}"
                           width="${ky033_ranger_width}"
                           length="${ky033_ranger_length}"
                           height="${ky033_ranger_thickness}"/>
      </inertial>
      <visual>
        <origin xyz="-0.010 0 -0.0105" rpy="${PI/2} 0 ${-PI/2}"/>
        <geometry>
          <mesh filename="package://airi_description/media/sensors/ky033.stl"
                scale="0.001 0.001 0.001"/>
        </geometry>
      </visual>
    </link>
    <gazebo reference="${name}_link">
      <sensor type="ray" name="${name}">
        <pose>0 0 0 0 0 0</pose>
        <visualize>false</visualize>
        <update_rate>10</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>5</samples>
              <resolution>1</resolution>
              <min_angle>${-8.0 * PI / 180.0}</min_angle>
              <max_angle>${8.0 * PI / 180.0}</max_angle>
            </horizontal>
            <vertical>
              <samples>5</samples>
              <resolution>1</resolution>
              <min_angle>${-8.0 * PI / 180.0}</min_angle>
              <max_angle>${8.0 * PI / 180.0}</max_angle>
            </vertical>
          </scan>
          <range>
            <min>0.0</min>
            <max>0.025</max>
            <resolution>0.005</resolution>
          </range>
        </ray>
        <plugin name="${name}_controller" filename="libgazebo_ros_range.so">
          <topicName>${name}</topicName>
          <frameName>${name}_link</frameName>
          <gaussianNoise>0.0025</gaussianNoise>
          <radiation>INFRARED</radiation>
          <!-- See https://www.vishay.com/docs/80107/80107.pdf for reference -->
          <fov>${2 * 8.0 * PI / 180.0}</fov>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>

  <xacro:property name="gy521_imu_mass" value="0.020"/>
  <xacro:property name="gy521_imu_thickness" value="0.0016"/>
  <xacro:property name="gy521_imu_length" value="0.0254"/>
  <xacro:property name="gy521_imu_width" value="0.01524"/>

  <xacro:macro name="gy521-imu" params="name">
    <link name="${name}_link">
      <inertial>
        <origin xyz="0 0 ${gy521_imu_thickness / 2}" rpy="0 0 ${PI/2}"/>
        <mass value="${gy521_imu_mass}"/>
        <xacro:box_inertia mass="${gy521_imu_mass}"
                           width="${gy521_imu_width}"
                           length="${gy521_imu_length}"
                           height="${gy521_imu_thickness}"/>
      </inertial>
      <visual>
        <origin xyz="-0.0127 -0.00762 0"/>
        <geometry>
          <mesh filename="package://airi_description/media/sensors/gy521.stl"
                scale="0.001 0.001 0.001"/>
        </geometry>
      </visual>
    </link>
    <gazebo reference="${name}_link">
      <sensor type="imu" name="${name}">
        <pose>0 0 0 0 0 0</pose>
        <visualize>false</visualize>
        <update_rate>10</update_rate>
        <plugin name="${name}_controller" filename="libgazebo_ros_imu_sensor.so">
          <topicName>${name}</topicName>
          <frameName>${name}_link</frameName>
          <gaussianNoise>0.005</gaussianNoise>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>

</robot>
