scan_filter_chain:
  - name: range_bounds
    type: laser_filters/LaserScanRangeFilter
    params:
      use_message_range_limits: false
      lower_threshold: 0.25
      upper_threshold: .inf
      lower_replacement_value: -.inf
      upper_replacement_value: .inf
      #  - name: angular_bounds
      #type: laser_filters/LaserScanAngularBoundsFilter
      #params:
      #lower_angle: -2.356
      #upper_angle: 2.356
